### ISSUE TITLE
Use of your scripts for a school project

### ISSUE THREAD

**Issue by compSciKai** [PCJohn/Script-Analyzer#1]
Hello,

I'm a student at Simon Fraser University in British Columbia, Canada. I'm wondering if we can use your script for a school project? We will include citations to prove this is your work, and we have your permission.

Thanks, 
Kainoa

**Comment by PCJohn** [comment]
Sure. It's an old, fun project.
Feel free to use it.

Prithvi

**Comment by compSciKai** [comment]
Thanks for your permission!

Cheers
